POST http://127.0.0.1:3000/services/request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjMsInJvbGUiOiJDbGllbnQiLCJpYXQiOjE3MzI0OTg2OTUsImV4cCI6MTczMjQ5OTU5NX0.Rosa0Yo1nQN1nSQcMoBJepLSSV0Lj9aAmBeWepeTRZ4

{
    "serviceId": 1
}