### regust service
POST http://127.0.0.1:3000/services/request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjUsInJvbGUiOiJDbGllbnQiLCJpYXQiOjE3MzI1MTYwNTYsImV4cCI6MTczMjUxNjk1Nn0.IOrSYIZ_SVgtmMv6N4MY6x1z3bL0X7OJjhgBPyox4y4

{
    "serviceId": 1
}

### Get all services by user ID
POST http://127.0.0.1:3000/users/client-requests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjUsInJvbGUiOiJDbGllbnQiLCJpYXQiOjE3MzI1MTg2NTUsImV4cCI6MTczMjUxOTU1NX0.vJ56AOgucKptVLvvrVw-bb_armDsmhRE0hgrx_RrT40

### getProfile ###

POST http://127.0.0.1:4000/users/get-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjYsInJvbGUiOiJDbGllbnQiLCJpYXQiOjE3MzI2NzE5NzAsImV4cCI6MTczMjY3Mjg3MH0.8RJJg_iywkrSJbogW97trfgGXVbStPOWoZWV8p1SmzU



